export const STR = {
  appName: 'Goooooal',
  tagline: 'Never Miss a World Cup Moment',
  welcome_desc: 'Put your phone down. We\'ll alert you the second something incredible is about to happen.',
  feature_goals: 'Instant goal alerts for your team',
  feature_shots: 'Near miss & shot-on-target warnings',
  feature_red: 'Red cards, penalties & VAR decisions',
  feature_notif: 'Works even when your phone is locked',
  start_btn: 'Get Started',
  permission_title: 'Enable Alerts',
  permission_text: 'Allow Goooooal to notify you when your team is about to score or when drama unfolds — so you can look up at the right moment.',
  allow_btn: 'Allow Notifications',
  skip_btn: 'Skip for now',
  team_title: 'Choose Your Team',
  team_subtitle: 'We\'ll alert you for every key moment',
  team_search: '🔍  Search teams...',
  watch_btn: 'Start Watching',
  live_badge: 'LIVE',
  look_up: 'LOOK UP NOW 👆',
  match_begin: 'Match is about to begin...',
  start_sim: '▶ Start Match Simulation',
  match_running: '🔴 Match in Progress...',
  match_done: '✅ Match Complete',
  settings_title: '🔔 Alert Settings',
  done_btn: 'Done',
  tap_continue: 'Tap to continue',
  alert_goal: '⚽ GOOOOOAL!',
  alert_shot: '🎯 Shot on Target!',
  alert_near: '😱 Near Miss!',
  alert_red: '🔴 Red Card!',
  alert_half: '🔔 Half Time!',
  alert_full: '🏁 Full Time!',
  notif_title: '⚽ Goooooal',
};
